### ISSUE TITLE
Invalid damping values error

### ISSUE THREAD

**Issue by geoport** [Caltech-geoquake/PySeismoSoil#19]
For a soil layer with the following properties I get "ValueError: The provided damping values must be between [0, 100]." error. 
Thk : 7 m
Vs : 300 m/s
Damping : 2%
Density : 1500 kg/m3

**Comment by geoport** [comment]
You can try to run Pipeline_05_Nonlinear_Method.ipynb with the following vs_profile 
`vs_matrix = np.array([[7, 300, 0.01, 1500, 1]])
vs_profile = Vs_Profile(vs_matrix,add_halfspace=True)`

after running `sim_results = nl_sim.run(
      show_fig=True, 
      save_txt=False, 
      remove_sim_dir=True,
  )`
it throws `ValueError: The provided damping values must be between [0, 100].` error. I know how to disable this error but I wonder if I should.

**Comment by xia-fr** [comment]
Hello, this has been addressed in #22 .

From the notes:
For nonlinear simulations, the dummy curves for ggmax and xi are now created separately from their corresponding calibrated parameters. The values contained in these dummy curves are not consequential for the simulations, but previously both the ggmax and xi curves were generated off of only the ggmax parameters. This would occasionally trigger a ValueError related to unrealistic damping values, since the ggmax parameters are only calibrated to guarantee the shape of the ggmax curve.
